/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/pki/ca.crt': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get CA certificates
     * @description Download root CA certificate(s) for trust store installation.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description PEM-encoded CA certificate(s) */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/x-pem-file': string
          }
        }
        /** @description CA certificates not available */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/pki/crl.pem': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Certificate Revocation List
     * @description Download current CRL for certificate validation.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description PEM-encoded CRL */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/x-pem-file': string
          }
        }
        /** @description CRL not available */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/pki/sign': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sign CSR
     * @description Signs a certificate signing request. Requires koios-factory role.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'multipart/form-data': {
            /** @description PEM-encoded CSR */
            csr: string
          }
        }
      }
      responses: {
        /** @description Certificate chain (leaf + intermediates + root) */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/x-pem-file': string
          }
        }
        /** @description Invalid CSR */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing koios-factory role */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Signing failed */
        502: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/pki/ds_params': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get device parameters */
    get: {
      parameters: {
        query?: never
        header: {
          /** @description Device identifier */
          'x-device-id': string
        }
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Device parameters */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['DsParams']
          }
        }
        /** @description Invalid device ID */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Device not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /** Store device parameters */
    post: {
      parameters: {
        query?: never
        header: {
          /** @description Device identifier */
          'x-device-id': string
        }
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['DsParams']
        }
      }
      responses: {
        /** @description Result */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'created' | 'exists'
            }
          }
        }
        /** @description Invalid request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/license/checkout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Start license purchase
     * @description Creates a Stripe checkout session. Returns URL to redirect user for payment.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CheckoutRequest']
        }
      }
      responses: {
        /** @description Checkout URL */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CheckoutResponse']
          }
        }
        /** @description Invalid key_type or return_url */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Stripe error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/license/checkout/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Stripe callback
     * @description Handles Stripe redirect after payment. Generates license key and redirects to return_url with license_key parameter.
     */
    get: {
      parameters: {
        query: {
          session_id: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Redirect to return_url with license_key */
        302: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid or incomplete session */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Processing failed */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/license/redeem': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Redeem license key
     * @description Validates license key, signs CSR, marks key as used. Keys can only be redeemed once.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['RedeemRequest']
        }
      }
      responses: {
        /** @description Certificate chain */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/x-pem-file': string
          }
        }
        /** @description Invalid CSR or key already used */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid license key */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Signing failed */
        502: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    DsParams: {
      ds_key_id: number
      rsa_len: number
      /** @description Base64 cipher text */
      cipher_c: string
      /** @description Base64 IV */
      iv: string
    }
    CheckoutRequest: {
      /**
       * @description License type
       * @enum {string}
       */
      key_type: 'matrx' | 'lantern'
      /**
       * Format: uri
       * @description Redirect URL after payment (must be whitelisted)
       */
      return_url: string
    }
    CheckoutResponse: {
      /**
       * Format: uri
       * @description Stripe checkout URL
       */
      url: string
    }
    RedeemRequest: {
      /**
       * @description License key from checkout
       * @example A1B2-C3D4-E5F6-G7H8-I9J0-K1L2-M3N4-O5P6
       */
      license_key: string
      /** @description PEM-encoded CSR */
      csr: string
    }
    Error: {
      /** @description Error message */
      error: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
